# =======================================
# SPRING BOOT CORE
# =======================================
spring:
  application:
    name: mentor
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # --- Caching & Redis ---
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      # password: ${SPRING_REDIS_PASSWORD}

  # --- File Upload ---
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# =======================================
# SERVER CONFIGURATION
# =======================================
server:
  port: 8080

# =======================================
# CUSTOM APPLICATION PROPERTIES
# =======================================
file:
  upload-dir: uploads/images

jwt:
  secret: ${JWT_SECRET}

swagger:
  server-url: ${SWAGGER_SERVER_URL}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE