# =======================================
# SPRING BOOT CORE
# =======================================
spring:
  application:
    name: mentor
  # --- JPA & Datasource Configuration ---
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bgitu}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:qwe}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  # --- Caching & Redis ---
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:} #
  # --- File Upload ---
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# =======================================
# SERVER CONFIGURATION
# =======================================
server:
  port: 8080

# =======================================
# CUSTOM APPLICATION PROPERTIES
# =======================================
file:
  upload-dir: uploads/images


jwt:
  secret: ${JWT_SECRET}

swagger:
  server-url: ${SWAGGER_SERVER_URL:http://localhost:8080}