# Настройки, которые ПЕРЕОПРЕДЕЛЯЮТ базовые для PROD-профиля
spring:
  jpa:
    hibernate:
      # В PROD мы только проверяем схему, но не меняем ее
      ddl-auto: validate
    # В PROD SQL-запросы в логах не нужны
    show-sql: false

  # Отключаем DevTools в проде на всякий случай
  devtools:
    add-properties: false

# В PROD нам нужен более строгий уровень логирования
logging:
  level:
    root: INFO
    com.bgitu.mentor: INFO # или WARN для еще меньшего количества логов