version: '3.8'

services:
  app:
    build: .
    container_name: mentor-app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/bgitu
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=qwe
      - SWAGGER_SERVER_URL=http://89.22.225.116:8080
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - db
      - redis


  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: bgitu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 1@ya.ru
      PGADMIN_DEFAULT_PASSWORD: "qweqwe"
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  pgadmin_data:
